# Generated by Django 5.1.3 on 2025-06-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_accounts', models.IntegerField(default=0)),
                ('active_loan_requests', models.IntegerField(default=0)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_loans', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_bankrupt', models.BooleanField(default=False)),
            ],
        ),
    ]
