# Generated by Django 5.1.3 on 2025-06-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bankprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankprofile',
            name='total_loans',
            field=models.IntegerField(default=0),
        ),
    ]
